
# Set all envs
export PYTHONPATH=`pwd`:$PYTHONPATH
export PATH=`pwd`/scripts:$PATH

# 
export ORCHESTRA_BASEPATH=$PWD
export ORCHESTRA_DATABASE_VOLUME="$HOME/volume"
export ORCHESTRA_DATABASE_HOST="postgresql://postgres:postgres@146.164.147.44:5432/orchestra"
export ORCHESTRA_EMAIL_FROM="cluster@lps.ufrj.br"
export ORCHESTRA_EMAIL_TO="jodafons@lps.ufrj.br"
export ORCHESTRA_EMAIL_TOKEN="@LPS_Cluster#2019"



# All envs should be set to singularity
export SINGULARITYENV_ORCHESTRA_DATABASE_VOLUME=$ORCHESTRA_DATABASE_VOLUME
export SINGULARITYENV_ORCHESTRA_DATABASE_HOST=$ORCHESTRA_DATABASE_HOST
export SINGULARITYENV_ORCHESTRA_EMAIL_FROM=$ORCHESTRA_EMAIL_FROM
export SINGULARITYENV_ORCHESTRA_EMAIL_TO=$ORCHESTRA_EMAIL_TO
export SINGULARITYENV_ORCHESTRA_EMAIL_TOKEN=$ORCHESTRA_EMAIL_TOKEN
export SINGULARITYENV_ORCHESTRA_BASEPATH=$ORCHESTRA_BASEPATH


