version: '3.5'

services:

  executor_server:
    container_name: executor-server
    image: ${DOCKER_NAMESPACE}/executor-server
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 80"]
    environment:
      PILOT_SERVER_HOST: ${PILOT_SERVER_HOST} # server
      EXECUTOR_SERVER_PORT: ${EXECUTOR_SERVER_PORT} # me
      EXECUTOR_SERVER_DEVICE: "-1"
      EXECUTOR_SERVER_MAX_RETRY: "5"
      EXECUTOR_SERVER_TIMEOUT: "60" # seconds
      EXECUTOR_SERVER_SLOTS_SIZE: "1"
      EXECUTOR_LOGGER_LEVEL: "DEBUG"
      EXECUTOR_PARTITION: "cpu"
    ports:
      - "${EXECUTOR_SERVER_PORT}:80"
    depends_on:
      - pilot_server  

  postman_server:
    container_name: postman-server
    image: ${DOCKER_NAMESPACE}/postman-server
    ports:
      - "${POSTMAN_SERVER_PORT}:80"
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 80"]
    environment:
      POSTMAN_SERVER_EMAIL_FROM: ${POSTMAN_SERVER_EMAIL_FROM}
      POSTMAN_SERVER_EMAIL_PASSWORD: ${POSTMAN_SERVER_EMAIL_PASSWORD}


  schedule_server:
    container_name: schedule-server
    image: ${DOCKER_NAMESPACE}/schedule-server
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 80"]
    environment:
      DATABASE_SERVER_HOST: ${DATABASE_SERVER_HOST}
      POSTMAN_SERVER_HOST: ${POSTMAN_SERVER_HOST}
      SCHEDULE_SERVER_RECREATE: "true" # recreate database
      SCHEDULE_LOGGER_LEVEL: "DEBUG"
    ports:
      - "${SCHEDULE_SERVER_PORT}:80"
    depends_on:
      - postman_server
      - database_server

  pilot_server:
    container_name: pilot-server
    image: ${DOCKER_NAMESPACE}/pilot-server
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 80"]
    environment:
      DATABASE_SERVER_HOST: ${DATABASE_SERVER_HOST}
      POSTMAN_SERVER_HOST: ${POSTMAN_SERVER_HOST}
      SCHEDULE_SERVER_HOST: ${SCHEDULE_SERVER_HOST}
      EXECUTOR_SERVER_BINDS: ${EXECUTOR_SERVER_BINDS}
      PILOT_AVAILABLE_PARTITIONS: ${PILOT_AVAILABLE_PARTITIONS}
      PILOT_LOGGER_LEVEL: "DEBUG"
    ports:
      - "${PILOT_SERVER_PORT}:80"
    depends_on:
      - postman_server
      - database_server
      - schedule_server

  database_server:
    container_name: database-server
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "${DATABASE_SERVER_PORT}:5432"
    volumes:
      - ${DATABASE_SERVER_DATA_PATH}:/var/lib/postgresql/data
      






  