


version: '3.5'

services:
  
  database_server:
    container_name: database-server
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ${HOME}/.postgresql/data:/var/lib/postgresql/data
      

