version: '3.5'

services:

  postman_server:
    container_name: postman-server
    image: ${DOCKER_NAMESPACE}/postman-server
    ports:
      - "${POSTMAN_SERVER_PORT}:80"
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 80"]
    environment:
      POSTMAN_SERVER_EMAIL_FROM: ${POSTMAN_SERVER_EMAIL_FROM}
      POSTMAN_SERVER_EMAIL_PASSWORD: ${POSTMAN_SERVER_EMAIL_PASSWORD}


  schedule_server:
    container_name: schedule-server
    image: ${DOCKER_NAMESPACE}/schedule-server
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 80"]
    environment:
      DATABASE_SERVER_HOST: ${DATABASE_SERVER_HOST}
      POSTMAN_SERVER_HOST: ${POSTMAN_SERVER_HOST}
      SCHEDULE_LOGGER_LEVEL: "INFO"
    ports:
      - "${SCHEDULE_SERVER_PORT}:80"
    depends_on:
      - postman_server

  pilot_server:
    container_name: pilot-server
    image: ${DOCKER_NAMESPACE}/pilot-server
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 80"]
    environment:
      DATABASE_SERVER_HOST: ${DATABASE_SERVER_HOST}
      POSTMAN_SERVER_HOST: ${POSTMAN_SERVER_HOST}
      SCHEDULE_SERVER_HOST: ${SCHEDULE_SERVER_HOST}
      EXECUTOR_SERVER_BINDS: ${EXECUTOR_SERVER_BINDS}
      PILOT_LOGGER_LEVEL: "INFO"
    ports:
      - "${PILOT_SERVER_PORT}:80"
    depends_on:
      - postman_server
      - schedule_server
      






  