version: '3'
services:

  orchestra:
    container_name: orchestra_server
    image: jodafons/orchestra:server
    restart: always
    environment:
      ORCHESTRA_BASEPATH: /app
      ORCHESTRA_EMAIL_FROM: $ORCHESTRA_EMAIL_FROM
      ORCHESTRA_EMAIL_TO: $ORCHESTRA_EMAIL_TO
      ORCHESTRA_EMAIL_TOKEN: $ORCHESTRA_EMAIL_TOKEN
      ORCHESTRA_DATABASE_HOST: $ORCHESTRA_DATABASE_HOST
