FROM jodafons/orchestra-base:latest
LABEL maintainer "Joao Victor da Fonseca Pinto <jodafons@lps.ufrj.br>"
USER root
SHELL [ "/bin/bash", "-c" ]
WORKDIR /app
CMD ["maestro.py", "pilot", "run" ,"--master"]

